title: Appendix (ownCloud QuickStart)
description: This appendix includes specific QuickStart procedures for ownCloud server. 
show_downloads: false
google_analytics:
github: 
   is_project_page: false
theme: jekyll-theme-cayman
